# This file was generated by GoReleaser. DO NOT EDIT.
cask "atlas" do
  desc "Atlas deterministic code intelligence: symbols, calls, routes, impact, cross-repo."
  homepage "https://github.com/aziron-ai/atlas"
  version "0.1.25"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atlas"

  on_macos do
    on_intel do
      url "https://github.com/aziron-ai/atlas/releases/download/v0.1.25/atlas_0.1.25_darwin_amd64.tar.gz",
        verified: "github.com/aziron-ai/atlas/"
      sha256 "474d601c8dcae7bbc3becd122e744ce8be4951ab30f8ba738b1a9f9895201cac"
    end
    on_arm do
      url "https://github.com/aziron-ai/atlas/releases/download/v0.1.25/atlas_0.1.25_darwin_arm64.tar.gz",
        verified: "github.com/aziron-ai/atlas/"
      sha256 "936a87bd527a36b842ad6fe6450b48f4e267d559d1046c6e73e06cc69af4d4e2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aziron-ai/atlas/releases/download/v0.1.25/atlas_0.1.25_linux_amd64.tar.gz",
        verified: "github.com/aziron-ai/atlas/"
      sha256 "b000d5a9e0d1af09dc92b34a0e92fe1dac70c92ceeeb73a6d0bb92215e6adc18"
    end
    on_arm do
      url "https://github.com/aziron-ai/atlas/releases/download/v0.1.25/atlas_0.1.25_linux_arm64.tar.gz",
        verified: "github.com/aziron-ai/atlas/"
      sha256 "9c45549bf5f2c19ea92c8965c5cd73b5ac3b65277100009485f3e1343465e9cb"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atlas"]
    end
  end

  # No zap stanza required
end
