# This file was generated by GoReleaser. DO NOT EDIT.
cask "atlas" do
  desc "Atlas deterministic code intelligence: symbols, calls, routes, impact, cross-repo."
  homepage "https://github.com/aziron-ai/atlas"
  version "0.1.45"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atlas"

  on_macos do
    on_intel do
      url "https://github.com/aziron-ai/atlas/releases/download/v0.1.45/atlas_0.1.45_darwin_amd64.tar.gz",
        verified: "github.com/aziron-ai/atlas/"
      sha256 "8507b7bec6381da00a89180a05e04917556a255c1daf666723f27ac6d68c1814"
    end
    on_arm do
      url "https://github.com/aziron-ai/atlas/releases/download/v0.1.45/atlas_0.1.45_darwin_arm64.tar.gz",
        verified: "github.com/aziron-ai/atlas/"
      sha256 "7b9aaaaa03c654e6b35b1c540caeb589966e3c7fe556d39222e510d8494916df"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aziron-ai/atlas/releases/download/v0.1.45/atlas_0.1.45_linux_amd64.tar.gz",
        verified: "github.com/aziron-ai/atlas/"
      sha256 "0e297368d2aceeba02d81b074061ff8ae487000271703dc0e145dbecf432b919"
    end
    on_arm do
      url "https://github.com/aziron-ai/atlas/releases/download/v0.1.45/atlas_0.1.45_linux_arm64.tar.gz",
        verified: "github.com/aziron-ai/atlas/"
      sha256 "d759d66bf0af5e403cf565b40cfba6500b49ac3a2bc848613dfe42946f99e181"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atlas"]
    end
    # Auto-provision the atlas skill + MCP config for every assistant on this
    # machine (Claude desktop+CLI, Codex, Copilot, Cursor, Gemini). Runs as the
    # installing user with HOME available; best-effort so a provisioning hiccup
    # never fails the cask install — but NEVER silent (issue #8): a skipped
    # bootstrap leaves every assistant config pointing at the previous
    # (deleted) Caskroom version dir, and the assistants fail to spawn Atlas
    # with no user-visible error. The binary itself resolves the stable
    # <prefix>/bin launcher PATH-independently since v0.1.41, so this hook
    # succeeding is what heals configs written by older versions; on failure
    # we retry via the stable launcher, then tell the user exactly what to run.
    begin
      system_command "#{staged_path}/atlas", args: ["bootstrap"]
    rescue => e
      begin
        system_command "#{HOMEBREW_PREFIX}/bin/atlas", args: ["bootstrap"]
      rescue
        opoo "atlas bootstrap could not auto-register the MCP configs (#{e}). " \
             "Assistant registrations may still point at the previous version — " \
             "run `atlas bootstrap` once to repoint them at the stable launcher; " \
             "`atlas doctor` shows which registrations are stale."
      end
    end
  end

  # No zap stanza required
end
