# This file was generated by GoReleaser. DO NOT EDIT.
cask "atlas" do
  desc "Atlas deterministic code intelligence: symbols, calls, routes, impact, cross-repo."
  homepage "https://github.com/aziron-ai/atlas"
  version "0.1.31"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "atlas"

  on_macos do
    on_intel do
      url "https://github.com/aziron-ai/atlas/releases/download/v0.1.31/atlas_0.1.31_darwin_amd64.tar.gz",
        verified: "github.com/aziron-ai/atlas/"
      sha256 "df019d86c357442c6432a01c252ecb39a89fa749339828a7b69acc789f05c24f"
    end
    on_arm do
      url "https://github.com/aziron-ai/atlas/releases/download/v0.1.31/atlas_0.1.31_darwin_arm64.tar.gz",
        verified: "github.com/aziron-ai/atlas/"
      sha256 "b8f94ae649fc590355254a557f9764e25603caf0e234e5d9a5edbf6b36ca98ec"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/aziron-ai/atlas/releases/download/v0.1.31/atlas_0.1.31_linux_amd64.tar.gz",
        verified: "github.com/aziron-ai/atlas/"
      sha256 "7af6754fddf385340e275bee74db574b3a51d846ce96d2778ab3b32ab3986bed"
    end
    on_arm do
      url "https://github.com/aziron-ai/atlas/releases/download/v0.1.31/atlas_0.1.31_linux_arm64.tar.gz",
        verified: "github.com/aziron-ai/atlas/"
      sha256 "0dba1327636bc5577714038007d5fc41d8ff8040ce983d84d4a877e923f54cc9"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/atlas"]
    end
    # Auto-provision the atlas skill + MCP config for every assistant on this
    # machine (Claude desktop+CLI, Codex, Copilot, Cursor, Gemini). Runs as the
    # installing user with HOME available; best-effort so a provisioning hiccup
    # never fails the cask install.
    begin
      system_command "#{staged_path}/atlas", args: ["bootstrap"]
    rescue
      # ignore: `atlas bootstrap` (or first-run) can be run manually later
    end
  end

  # No zap stanza required
end
